version: '3.7'

services:
  keycloak:
    image: "quay.io/keycloak/keycloak-x:13.0.0"
    entrypoint: /opt/jboss/tools/docker-entrypoint.sh --auto-config --db=postgres -Dkc.db.url.host=postgres --db-username=keycloak --db-password=password --http-enabled=true
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    restart: on-failure
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    ports:
      - "8081:8080"
    links:
      - "postgres:postgres"
    depends_on:
      - postgres
  postgres:
    image: "postgres:11.0"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/dbdata
    restart: on-failure
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data/dbdata"
  elastic:
    image: elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
    restart: on-failure
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    ports:
      - "9201:9200"
    volumes:
      - "elastic:/usr/share/elasticsearch/data"
#  logstash:
#    build:
#      dockerfile: src/main/docker/Logstash.custom
#      context: .
#    restart: on-failure
#    ports:
#      - "12201:12201/udp"
#      - "9600:9600"
#    links:
#      - elastic:elasticsearch
#    depends_on:
#      - elastic
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.5.1
#    restart: on-failure
#    ports:
#      - "5601:5601"
#    links:
#      - elastic:elasticsearch
#    depends_on:
#      - elastic
#  infinispan:
#    image: infinispan/server:10.0.1.Final-1
#    environment:
#      USER: quarkus
#      PASS: quarkus
#    ports:
#      - "11222:11222"
#  artemis:
#    image: vromero/activemq-artemis:2.9.0-alpine
#    environment:
#      ARTEMIS_USERNAME: quarkus
#      ARTEMIS_PASSWORD: quarkus
#    ports:
#      - "8161:8161"
#      - "61616:61616"
#  pgadmin:
#    image: "dpage/pgadmin4:3.6"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: lgarin@gmx.ch
#      PGADMIN_DEFAULT_PASSWORD: 123
#    ports:
#      - "8084:80"
#    links:
#      - "postgres:postgres"
volumes:
  keycloak:
  postgres:
  elastic:
