version: '3.7'

services:
  keycloak:
    image: "jboss/keycloak:4.7.0.Final"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    volumes:
      - "keycloak:/opt/jboss/keycloak/standalone"
    ports:
      - "8081:8080"
    links:
      - "postgres:postgres"
    depends_on:
      - postgres
  postgres:
    image: "postgres:11.0"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/dbdata
    volumes:
      - "postgres:/var/lib/postgresql/data/dbdata"
  neo4j:
    image: neo4j:3.5.0
    environment:
      - discovery.type=single-node
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j:/var/lib/neo4j/data
#  pgadmin:
#    image: "dpage/pgadmin4:3.6"
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=lgarin@gmx.ch
#      - PGADMIN_DEFAULT_PASSWORD=123
#    ports:
#      - "8084:80"
#    links:
#      - "postgres:postgres"
volumes:
  keycloak:
  postgres:
  neo4j:
