version: '3.7'

services:
  keycloak:
    image: "jboss/keycloak:4.7.0.Final"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
#     KEYCLOAK_IMPORT: /opt/jboss/keycloak/standalone/tmp/realm-export.json
    volumes:
      - "keycloak:/opt/jboss/keycloak/standalone"
    ports:
      - "8081:8080"
    links:
      - "postgres:postgres"
    depends_on:
      - postgres
  postgres:
    image: "postgres:11.0"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/dbdata
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data/dbdata"
  elastic:
    image: elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - "elastic:/usr/share/elasticsearch/data"
#  artemis:
#    image: vromero/activemq-artemis:2.9.0-alpine
#    environment:
#      ARTEMIS_USERNAME: quarkus
#      ARTEMIS_PASSWORD: quarkus
#    ports:
#      - "8161:8161"
#      - "61616:61616"
#  pgadmin:
#    image: "dpage/pgadmin4:3.6"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: lgarin@gmx.ch
#      PGADMIN_DEFAULT_PASSWORD: 123
#    ports:
#      - "8084:80"
#    links:
#      - "postgres:postgres"
volumes:
  keycloak:
  postgres:
  elastic:
